const APPS_SCRIPT_URL =
  'https://script.google.com/macros/s/AKfycbwEy4avfNnBxdUieLNZUF3AmXrCqWMDq10r73QJ5vhgzkXWGDoeGvedZGHQnPGG3S9p/exec'

export async function POST(request) {
  try {
    const data = await request.json()

    await fetch(APPS_SCRIPT_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    })

    // TODO: Resend email integration (after May 5, 2026)
    // Send to: dave@canopycreativeco.com and hello@canopycreativeco.com
    // Attach: the PDF generated by the Google Apps Script webhook
    // Note: logoFileName and attachmentFileNames in the payload are file name strings only —
    // the actual file contents are not captured by the current form. To receive uploaded files,
    // implement client-side upload to a storage service (e.g. Cloudflare R2) at file-select time,
    // store the returned URL in the payload, and attach via URL when sending through Resend.
    // Alternatively, instruct clients to email attachments separately until this is implemented.

    return Response.json({ success: true })
  } catch (err) {
    console.error('Intake route error:', err)
    return Response.json({ success: false, error: err.message })
  }
}
